
footprint: [[-2, -1], [-2, 1], [2, 1], [2, -1]]
#robot_radius: ir_of_robot
inflation_radius: 0.55

plugins:
 - {name: obstacle, type: "costmap_2d::ObstacleLayer"}
 - {name: inflation, type: "costmap_2d::InflationLayer"}

transform_tolerance: 0.2

obstacle_layer:
 enabled: true
 obstacle_range: 50.0
 raytrace_range: 50.0
 inflation_radius: 0.5
 track_unknown_space: false
 combination_method: 1

obstacle:
  track_unknown_space: true
  observation_sources: lidar radar
  lidar: {sensor_frame: ego_vehicle/lidar/lidar1, data_type: PointCloud2, topic: /carla/ego_vehicle/processed_semantic_lidar/lidar1/point_cloud, marking: true, clearing: true, min_obstacle_height: 0.2}
  radar: {sensor_frame: ego_vehicle, data_type: PointCloud2, topic: /carla/ego_vehicle/radar/front/radar_points, marking: true, clearing: true, min_obstacle_height: 1}

inflation_layer:
  enabled:              true
  cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     1.0  # max. distance from an obstacle at which costs are incurred for planning paths.


#laser_scan_sensor: {sensor_frame: frame_name, data_type: LaserScan, topic: topic_name, marking: true, clearing: true}