obstacle_range: 40.0
raytrace_range: 40.0
footprint: [[-2, -1], [-2, 1], [2, 1], [2, -1]]
#robot_radius: ir_of_robot
inflation_radius: 0.50

plugins:
 - {name: obstacle, type: "psaf_obstacle_layer::PsafObstacleLayer"}
 - {name: inflation, type: "costmap_2d::InflationLayer"}


obstacle:
  track_unknown_space: false
  footprint_clearing_enabled: true
  observation_sources: lidar_marking_inner lidar_clearing_inner lidar_marking_outer lidar_clearing_outer
  combination_method: 0
  max_obstacle_height: 20
  # We use 2 different lidar sensors with different radii to increase the resolution more uniformly across the full range
  lidar_marking_inner: {sensor_frame: "", data_type: PointCloud2, topic: /carla/ego_vehicle/processed_semantic_lidar_inner/marking/point_cloud, marking: true, clearing: true, min_obstacle_height: 0, observation_persistence: 0.1, max_obstacle_height: 20.0}
  lidar_marking_outer: {sensor_frame: "", data_type: PointCloud2, topic: /carla/ego_vehicle/processed_semantic_lidar_outer/marking/point_cloud, marking: true, clearing: true, min_obstacle_height: 0, observation_persistence: 0.1, max_obstacle_height: 20.0}
  lidar_clearing_inner: {sensor_frame: "", data_type: PointCloud2, topic: /carla/ego_vehicle/processed_semantic_lidar_inner/clearing/point_cloud, marking: false, clearing: true, min_obstacle_height: 20.0, observation_persistence: 0.1, max_obstacle_height: 20.0}
  lidar_clearing_outer: {sensor_frame: "", data_type: PointCloud2, topic: /carla/ego_vehicle/processed_semantic_lidar_outer/clearing/point_cloud, marking: false, clearing: true, min_obstacle_height: 20.0, observation_persistence: 0.1, max_obstacle_height: 20.0}