obstacle_range: 40.0
raytrace_range: 40.0
footprint: [[-2, -1], [-2, 1], [2, 1], [2, -1]]
#robot_radius: ir_of_robot
inflation_radius: 0.5

plugins:
 - {name: obstacle, type: "costmap_2d::ObstacleLayer"}
 - {name: inflation, type: "costmap_2d::InflationLayer"}


obstacle:
  track_unknown_space: false
  footprint_clearing_enabled: true
  observation_sources: lidar_marking lidar_clearing #radar
  combination_method: 0
  max_obstacle_height: 20
  lidar_marking: {sensor_frame: "", data_type: PointCloud2, topic: /carla/ego_vehicle/processed_semantic_lidar/marking/point_cloud, marking: true, clearing: true, min_obstacle_height: 0, observation_persistence: 0.1, max_obstacle_height: 20.0}
  lidar_clearing: {sensor_frame: "", data_type: PointCloud2, topic: /carla/ego_vehicle/processed_semantic_lidar/clearing/point_cloud, marking: false, clearing: true, min_obstacle_height: 20.0, observation_persistence: 0.1, max_obstacle_height: 20.0}
  #radar: {sensor_frame: "", data_type: PointCloud2, topic: /carla/ego_vehicle/radar/front/radar_points, marking: false, clearing: true, min_obstacle_height: 0}


#laser_scan_sensor: {sensor_frame: frame_name, data_type: LaserScan, topic: topic_name, marking: true, clearing: true}