obstacle_range: 40.0
raytrace_range: 40.0
footprint: [[-2, -1], [-2, 1], [2, 1], [2, -1]]
#robot_radius: ir_of_robot
inflation_radius: 0.55

plugins:
 - {name: obstacle, type: "costmap_2d::ObstacleLayer"}
 - {name: inflation, type: "costmap_2d::InflationLayer"}



max_obstacle_height: 100 # bin mir unsicher an welcher stelle diese zeile eingefügt werden muss ^^

obstacle:
  track_unknown_space: true
  observation_sources: lidar #radar
  lidar: {sensor_frame: ego_vehicle/semantic_lidar, data_type: PointCloud2, topic: /carla/ego_vehicle/processed_semantic_lidar, marking: true, clearing: true, min_obstacle_height: -10, max_obstacle_height: 100}
  # radar: {sensor_frame: ego_vehicle, data_type: PointCloud2, topic: /carla/ego_vehicle/radar/front/radar_points, marking: true, clearing: true, min_obstacle_height: 1}


#laser_scan_sensor: {sensor_frame: frame_name, data_type: LaserScan, topic: topic_name, marking: true, clearing: true}