## Costmap converter plugin   
converter_plugin: "costmap_converter::CostmapToPolygonsDBSMCCH"
#converter_plugin: "costmap_converter::CostmapToLinesDBSRANSAC"
#converter_plugin: "costmap_converter::CostmapToLinesDBSMCCH"
#converter_plugin: "costmap_converter::CostmapToPolygonsDBSConcaveHull"
#converter_plugin: "" # deactivate plugin
costmap_converter_spin_thread: True
costmap_converter_rate: 5
polygon_marker_topic: "/costmap_converter/marker"
obstacles_topic: "/costmap_converter/costmap_obstacles"


costmap_converter/CostmapToPolygonsDBSMCCH:
  cluster_max_distance: 3.0
  cluster_min_pts: 2
  cluster_max_pts: 300
  convex_hull_min_pt_separation: 0.2

## Configure plugins (namespace move_base/TebLocalPlannerROS/PLUGINNAME)
## The parameters must be added for each plugin separately
costmap_converter/CostmapToLinesDBSRANSAC:
  cluster_max_distance: 3.0
  cluster_min_pts: 2
  ransac_inlier_distance: 0.5
  ransac_min_inliers: 10
  ransac_no_iterations: 2000
  ransac_remainig_outliers: 3
  ransac_convert_outlier_pts: False
  ransac_filter_remaining_outlier_pts: False
  convex_hull_min_pt_separation: 0.2