global_costmap:
  global_frame: map
  robot_base_frame: ego_vehicle
  update_frequency: 1.0
  update_frequency: 0.5
  static_map: true
  width: 1000.0
  height: 1000.0
  origin_x: -500.0
  origin_y: -500.0
  resolution: 1
  transform_tolerance: 0.5