local_costmap:
  global_frame: map #was odom previously
  robot_base_frame: ego_vehicle
  update_frequency: 2.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 40.0
  height: 40.0
  resolution: 0.75
  transform_tolerance: 1.0