#######################################################################################################################
# Message that Represents one waypoint in a route
#######################################################################################################################

# 3d position
float32 x
float32 y
float32 z

# Max speed
uint8 speed

# duration up to that waypoint within the lanelet
float32 duration

# distance up to that waypoint within the lanelet
float32 distance