#######################################################################################################################
# Message that includes the information of the segmentation, the rgb and the depth camera
#######################################################################################################################

# The segmentation image
sensor_msgs/Image segmentation

# The rgb image
sensor_msgs/Image rgb

# The depth image
sensor_msgs/Image depth