#######################################################################################################################
# Message that contains the information about a detected speed limit sign
#######################################################################################################################


#The relative position seen from the upper left corner
float32 x
float32 y

# the limit in km/H
uint8 limit