#######################################################################################################################
# Message that contains the information about a detected stop line on the road
#######################################################################################################################


#The relative position seen from the upper left corner
float32 x
float32 y

# distance in meters
float32 distance