#######################################################################################################################
# Message that contains the information that is needed start/update a p2p navigation
#######################################################################################################################

# id planning msg
uint8 id

# List of all lanlets, that are located on the route
Lanelet[] route
