weights: weights/yolov5m.pt
cfg: ''
data: trainCarlaSpeedSigns.yaml
hyp: hyp.traffic-signs.yaml
epochs: 250
batch_size: 28
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
log_imgs: 16
workers: 8
project: runs/train
name: yolov5m-e250-frozen_backbone
exist_ok: false
total_batch_size: 28
world_size: 1
global_rank: -1
save_dir: runs/train/yolov5m-e250-frozen_backbone
